name: Unity C# Linter

on:
  push:
  pull_request:

jobs:
  lint:
    name: Run C# Linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'

      - name: Install dotnet-format
        run: dotnet tool install -g dotnet-format

      - name: Run dotnet-format
        run: dotnet-format Assets/Scripts --check --folder --include **/*.cs --verbosity diagnostic
